# Generated by Django 2.0 on 2019-02-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='profiles_api.Course'),
        ),
    ]
